[bell]
animation = "EaseOutExpo"
duration = 0
color = "#ffffff"

[colors.bright]
black = "#6C6F85"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#BCC0CC"
yellow = "#DF8E1D"

[colors.cursor]
cursor = "#F5E0DC"
text = "#1E1E2E"

[colors.dim]
black = "#5C5F77"
blue = "#1E66F5"
cyan = "#179299"
green = "#40A02B"
magenta = "#EA76CB"
red = "#D20F39"
white = "#ACB0BE"
yellow = "#DF8E1D"

[colors.hints.end]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.hints.start]
background = "#F9E2AF"
foreground = "#1E1E2E"

[colors.normal]
black = "#51576D"
blue = "#8CAAEE"
cyan = "#81C8BE"
green = "#A6D189"
magenta = "#F4B8E4"
red = "#E78284"
white = "#B5BFE2"
yellow = "#E5C890"

[colors.primary]
background = "#1E1E2E"
bright_foreground = "#CDD6F4"
dim_foreground = "#CDD6F4"
foreground = "#CDD6F4"

[colors.search.focused_match]
background = "#A6E3A1"
foreground = "#1E1E2E"


[colors.search.matches]
background = "#A6ADC8"
foreground = "#1E1E2E"

[colors.selection]
background = "#F5E0DC"
text = "#1E1E2E"

[colors.vi_mode_cursor]
cursor = "#B4BEFE"
text = "#1E1E2E"

[cursor]
thickness = 0.2
unfocused_hollow = true
vi_mode_style = "Block"

[cursor.style]
blinking = "Off"
shape = "Block"

[env]
TERM = "xterm-256color"

[font]
builtin_box_drawing = true
size = 11.0

[font.bold]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold"

[font.bold_italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Bold Italic"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
family = "JetBrainsMono Nerd Font Mono"
style = "Italic"

[font.normal]
family = "JetBrainsMono Nerd Font Mono"
style = "SemiBold"

[font.offset]
x = 0
y = 0

[[keyboard.bindings]]
chars = "alacritty -e 'htop' & \r"
key = "Y"
mods = "Control"

[[keyboard.bindings]]
key = "F2"
mods = "Control"

[keyboard.bindings.command]
args = ["msg", "config", "window.opacity=0.90"]
program = "alacritty"

[[keyboard.bindings]]
key = "F2"
mods = "Control|Shift"

[keyboard.bindings.command]
args = ["msg", "config", "window.opacity=1"]
program = "alacritty"

[[keyboard.bindings]]
action = "ToggleFullscreen"
key = "F11"

[[mouse.bindings]]
action = "ExpandSelection"
mouse = "Right"

[[mouse.bindings]]
action = "ExpandSelection"
mods = "Control"
mouse = "Right"

[[mouse.bindings]]
action = "PasteSelection"
mode = "~Vi"
mouse = "Middle"

[scrolling]
history = 500
multiplier = 3

[selection]
save_to_clipboard = true

[shell]
args = ["-l", "-c", "tmux new-session -t main; tmux new-window || tmux new-session -s main"]
program = "/bin/sh"

[window]
decorations = "full"
decorations_theme_variant = "None"
dynamic_padding = true
dynamic_title = true
opacity = 1
title = "Alacritty"

[window.class]
general = "Alacritty"
instance = "Alacritty"

[window.dimensions]
columns = 0
lines = 0

[window.padding]
x = 0
y = 0

[window.position]
x = 0
y = 0
