#!/bin/bash

bat=/sys/class/power_supply/BAT1/
per="$(cat "$bat/capacity")"


color() {
	line="$(acpi --ac-adapter | cut -d ":" -f 2 | xargs)"
	if [[ "$line" == "off-line" ]]; then
		echo "#cba6f7"
	else
		echo "#fab387"
	fi
}


percent() {
echo "$per"
}

[ "$1" = "color" ] && color && exit
[ "$1" = "percent" ] && percent && exit
exit
