#!/bin/bash

hypr_spaces() {
	WORKSPACE_WINDOWS=$(hyprctl workspaces -j | jq 'map({key: .id | tostring, value: .windows}) | from_entries')
	seq 1 9 | jq --argjson windows "${WORKSPACE_WINDOWS}" --slurp -Mc 'map(tostring) | map({id: ., windows: ($windows[.]//0)})'
}

clamp() {
	min=$1
	max=$2
	val=$3
	python -c "print(max($min, min($val, $max)))"
}

hypr_get_workspaces() {
	hypr_spaces
	socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - | while read -r line; do
	hypr_spaces
done
}

hypr_get_active_workspace() {
	hyprctl monitors -j | jq '.[] | select(.focused) | .activeWorkspace.id'

	socat -u UNIX-CONNECT:$XDG_RUNTIME_DIR/hypr/$HYPRLAND_INSTANCE_SIGNATURE/.socket2.sock - |
		stdbuf -o0 awk -F '>>|,' -e '/^workspace>>/ {print $2}' -e '/^focusedmon>>/ {print $3}'
	}

hypr_change_workspace() {
	direction=$1
	current=$2
	echo $direction $current $1
	if test "$direction" = "down"
	then
		target=$(clamp 1 9 $(($current+1)))
		echo "jumping to $target"
		hyprctl dispatch workspace "$target"
	elif test "$direction" = "up"
	then
		target=$(clamp 1 9 $(($current-1)))
		echo "jumping to $target"
		hyprctl dispatch workspace "$target"
	fi
}

# ----

niri_get_workspaces() {
	niri msg --json event-stream | stdbuf -oL jq -c "if .WorkspacesChanged != null then [.WorkspacesChanged.workspaces[] | {id: .idx, idh: .id, windows: .active_window_id // 0}] else empty end | sort_by(.id)"
}

niri_get_active_workspace() {
	niri msg --json workspaces | jq ".[] | select(.is_active == true) | .idx"

	niri msg --json event-stream | stdbuf -oL jq -c "if .WorkspaceActivated != null then .WorkspaceActivated.id else empty end"
}

niri_change_workspace() {
	direction=$1
	if test "$direction" = "down"
	then
		niri msg -j action focus-workspace-down
	elif test "$direction" = "up"
	then
		niri msg -j action focus-workspace-up
	fi
}

if [[ $1 == "get" ]]; then
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		hypr_get_workspaces
	elif [[ $XDG_CURRENT_DESKTOP == "niri" ]]; then
		niri_get_workspaces
	fi
elif [[ $1 == "get-active" ]]; then
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		hypr_get_active_workspace
	elif [[ $XDG_CURRENT_DESKTOP == "niri" ]]; then
		niri_get_active_workspace
	fi
elif [[ $1 == "change" ]]; then
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		hypr_change_workspace "$2" "$3"
	elif [[ $XDG_CURRENT_DESKTOP == "niri" ]]; then
		niri_change_workspace "$2"
	fi
elif [[ $1 == "change-to" ]]; then
	if [[ $XDG_CURRENT_DESKTOP == "Hyprland" ]]; then
		hyprctl dispatch workspace "$2"
	elif [[ $XDG_CURRENT_DESKTOP == "niri" ]]; then
		niri msg -j action focus-workspace "$2"
	fi
fi
