#!/bin/bash

## Files and cmd
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

## Run eww daemon if not running already
if [[ ! `pidof eww` ]]; then
	${EWW} daemon
	sleep 1
fi

restart=""
if [[ "$1" = "restart" ]]; then
	restart="--restart"
fi

## Open widgets 
run_eww() {
	${EWW} --config "$CFG" open-many $restart \
		   background \
		   profile \
		   system \
		   clock \
		   uptime \
		   github \
		   reddit \
		   whatsapp \
		   youtube \
		   apps \
		   logout \
		   sleep \
		   reboot \
		   poweroff \
		   folders \
		   weather \
		   music \
		   calendar
}

## Launch or close widgets accordingly
if [[ ! -f "$FILE" ]]; then
	touch "$FILE"
	run_eww
else
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit whatsapp youtube weather apps logout sleep reboot poweroff folders calendar
	rm "$FILE"
fi
