#!/bin/bash

## Open folders in nautilus
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit whatsapp youtube weather apps mail logout sleep reboot poweroff folders calendar
	rm -rf "$FILE"
}

if [[ "$1" == "--dl" ]]; then
	close_dash && nautilus ~/Downloads &

elif [[ "$1" == "--docs" ]]; then
	close_dash && nautilus ~/Documents &

elif [[ "$1" == "--music" ]]; then
	close_dash && nautilus ~/Music &

elif [[ "$1" == "--pics" ]]; then
	close_dash && nautilus ~/Pictures &

elif [[ "$1" == "--cfg" ]]; then
	close_dash && nautilus ~/.config &

elif [[ "$1" == "--local" ]]; then
	close_dash && nautilus ~/.local/share &

fi
