#!/bin/bash

## Open Applications
FILE="$HOME/.cache/eww_launch.dashboard"
CFG="$HOME/.config/eww/dashboard"
EWW=`which eww`

close_dash() {
	${EWW} --config "$CFG" close \
					background profile system clock uptime music github \
					reddit whatsapp youtube weather apps mail logout sleep reboot poweroff folders calendar
	rm -rf "$FILE"
}

if [[ "$1" == "--ff" ]]; then
	close_dash && firefox &

elif [[ "$1" == "--tr" ]]; then
	close_dash && kitty --working-directory ~ &

elif [[ "$1" == "--fm" ]]; then
	close_dash && nautilus ~ &

elif [[ "$1" == "--cd" ]]; then
	close_dash && codium &

elif [[ "$1" == "--gp" ]]; then
	close_dash && gimp &

elif [[ "$1" == "--vb" ]]; then
	close_dash && virtualbox &

elif [[ "$1" == "--sl" ]]; then
	spotify-launcher &

fi
